
name: tiktok_lite
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.4.10

flutter:
  uses-material-design: true
    